version: '3.8'
services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@my-postgres-db:5432/mydb?schema=public
      - CLIENT_ID=1158667847225069638
      - OSU_CLIENT_ID=10319
      - OSU_CLIENT_SECRET=b0m4ZsxjrpoIMGsya3kkRP8QYwyFuUBXoMkQ43CS
      - BOT_TOKEN=MTE1ODY2Nzg0NzIyNTA2OTYzOA.Gn34P8.6BTihl40ipeB0zsaXTa_hq3Gdp-8erJC68cpkg
    depends_on:
      - my-postgres-db
    ports:
      - "3000:3000" # Replace with the port your app uses

  my-postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
